language: perl
perl: '5.32'
before_deploy: bash tools/create-module-package.sh
deploy:
  provider: releases
  file: dist/perl-Program.tar.gz
  api_key:
    secure:
      secure: "aQ0IA4SaPM9GganCQSOaBYiwq5STFO3qJxyD2ZwdY54ND71YpsI35BWomYY3dckhnbTLpYuwqNhgSSKErVwA6J18aVtQFzyi6DgdCsWh/Ia8ENp52wry4z/y+AwCKAPCn5nscdE18zXseES+ePdHfeE5OO4OMP46me27hxAaNeB7DxHN0uxDDPaiGyHrfDBQ6rX8mRk4UZWnCkomYLhLCtB4zETn3Qb6oVDMHoyL0eZCNqEKYOkdLHeXzwl8p7TQc7Bw7A5Crv3Jvt3PhFT6TPXK2PwOdfi/sZY8jpMxDSrHxRWMsvDBfObqi0kCrFhlHIw0KPkAssDm6LNOT7ojbK1ji47oU5RunyeEvCTADhbcDBYuIHDVM6lsN47K556cK1FFNK3l0qYy5FEjlVrlQw+HJdmccZ7wFo8waN0H4Oa2UaUlwulpQMkshoS76/NnCkGHN5H9f2MKJQ1Z7jbLmz/liZjiE4V5r3TwFY0/xw8nw1QjwKKgFqa280RN9APAIPIUmEzcYyxU4+KN7MyxZgBfFJoOrubML12IGgfFUY2/QbzzMQy+PkT/rXg05FJVc8P6ssCLRqDlOp6HOz/Dt4VsfmkN7KqCEFmnyLccNnebX9VKLbzOpACnNt7WDYlpBeG1NgAlkgocLNeAPoI1uhRw4vTvHkvtCk4w1aZhJXM="
  skip_cleanup: true
  on:
    tags: true
  prerelease: true