language: perl
perl: '5.32'
before_deploy: make clean && bash tools/create-module-package.sh
deploy:
  provider: releases
  file: dist/perl-Program.tar.gz
  api_key:
    secure: "jrCqZLvxeg1tegeS0ISV9wAOBkHMn5hKdixHoD51CeruFWeohsLzeujB47zitGYs7PalNrcBFRU0CGJA3BVSE97CqCgDmfiM6uk7FS8KWHyj87gFeunGkV03x3LV0siLVq8AvkaElAEc1f2H6f1LOUBzUc7axsgymyU90VTk2H2/xZKpvgtkmpR1J9oJE5/WB5/cEoI2aaU815HPBo5Ptp1+qZOGIyGfCa/19rspBh9bOSVXDQ16W3RzQ2SVVNdigFvcHI8600kzgsqgq07BzABqGc1TNwVRdeFQP+fKvBec0UnVJO1loKAaRe3pDZa1i0URGgXXor/nhHDfWZF0usSmNbcl8ymZPltnC2Pyt7+c9NdljYHlmzMT9z8JLlxHAFc+p0CU+p3BvHemVor082qHGKrGwD701baoMknInfRU1eoKk8NIQruFLDaTwh34KKtnt5vQGChCGViL1pSM6dxebVosVt1EVPofdn5+lOyFHk6LuXFNLLkjhUf55FRHwBmG9kbeWjUoKM+fgGGZK34E2gshs4z6bOob1ZGne0C/KFb2TKcUKqrpz59Se00C6GWAKS/9Z3BJUSkqFKj4Q+jyJaEsXmbrVFEsVx0sjOqjGoKdFtP+XBoaPbhgxJoIw9D/7akQkvZ+8iZbWpjb29VrVU2PTdwUgXRuySS7mVU="
  skip_cleanup: true
  on:
    tags: true
  prerelease: true